export enum KeyboardKey {
  Q,
  W,
  E,
  R,
  T,
  Y,
  U,
  I,
  O,
  P,
  A,
  S,
  D,
  F,
  G,
  H,
  J,
  K,
  L,
  Z,
  X,
  C,
  V,
  B,
  N,
  M,
  Shift,
  Caps,
  Tab,
  Space,
  Enter,
  Up,
  Left,
  Down,
  Right,
  Insert,
  Home,
  End,
  PageUp,
  PageDown,
  Backspace,
  Delete,
  Num1,
  Num2,
  Num3,
  Num4,
  Num5,
  Num6,
  Num7,
  Num8,
  Num9,
  Num0,
  Backtick,
  Tilde,
  ExclamationPoint,
  AtSymbol,
  HashSign,
  DollarSign,
  Percent,
  Caret,
  Ampersand,
  Asterix,
  LeftParenthesis,
  RightParenthesis,
  Dash,
  Underscore,
  Equals,
  Plus,
  LeftSquareBracket,
  RightSquareBracket,
  LeftCurlyBrace,
  RightCurlyBrace,
  Semicolon,
  Colon,
  SingleQuote,
  DoubleQuote,
  Comma,
  Period,
  LessThan,
  GreaterThan,
  QuestionMark,
  ForwardSlash,
  BackSlash,
  PipeSymbol
};

export const KeysByKeyCode = new Map<string, KeyboardKey>([
  ['Shift', KeyboardKey.Shift],
  ['CapsLock', KeyboardKey.Caps],
  ['Tab', KeyboardKey.Tab],
  [' ', KeyboardKey.Space],
  ['Spacebar', KeyboardKey.Space],
  ['Enter', KeyboardKey.Enter],
  ['ArrowUp', KeyboardKey.Up],
  ['ArrowLeft', KeyboardKey.Left],
  ['ArrowRight', KeyboardKey.Right],
  ['ArrowDown', KeyboardKey.Down],
  ['PageUp', KeyboardKey.PageUp],
  ['PageDown', KeyboardKey.PageDown],
  ['End', KeyboardKey.End],
  ['Delete', KeyboardKey.Delete],
  ['Insert', KeyboardKey.Insert],
  ['Home', KeyboardKey.Home],
  ['Backspace', KeyboardKey.Backspace],
  ['1', KeyboardKey.Num1],
  ['2', KeyboardKey.Num2],
  ['3', KeyboardKey.Num3],
  ['4', KeyboardKey.Num4],
  ['5', KeyboardKey.Num5],
  ['6', KeyboardKey.Num6],
  ['7', KeyboardKey.Num7],
  ['8', KeyboardKey.Num8],
  ['9', KeyboardKey.Num9],
  ['0', KeyboardKey.Num0],
  ['q', KeyboardKey.Q],
  ['w', KeyboardKey.W],
  ['e', KeyboardKey.E],
  ['r', KeyboardKey.R],
  ['t', KeyboardKey.T],
  ['y', KeyboardKey.Y],
  ['u', KeyboardKey.U],
  ['i', KeyboardKey.I],
  ['o', KeyboardKey.O],
  ['p', KeyboardKey.P],
  ['a', KeyboardKey.A],
  ['s', KeyboardKey.S],
  ['d', KeyboardKey.D],
  ['f', KeyboardKey.F],
  ['g', KeyboardKey.G],
  ['h', KeyboardKey.H],
  ['j', KeyboardKey.J],
  ['k', KeyboardKey.K],
  ['l', KeyboardKey.L],
  ['z', KeyboardKey.Z],
  ['x', KeyboardKey.X],
  ['c', KeyboardKey.C],
  ['v', KeyboardKey.V],
  ['b', KeyboardKey.B],
  ['n', KeyboardKey.N],
  ['m', KeyboardKey.M],
  ['Q', KeyboardKey.Q],
  ['W', KeyboardKey.W],
  ['E', KeyboardKey.E],
  ['R', KeyboardKey.R],
  ['T', KeyboardKey.T],
  ['Y', KeyboardKey.Y],
  ['U', KeyboardKey.U],
  ['I', KeyboardKey.I],
  ['O', KeyboardKey.O],
  ['P', KeyboardKey.P],
  ['A', KeyboardKey.A],
  ['S', KeyboardKey.S],
  ['D', KeyboardKey.D],
  ['F', KeyboardKey.F],
  ['G', KeyboardKey.G],
  ['H', KeyboardKey.H],
  ['J', KeyboardKey.J],
  ['K', KeyboardKey.K],
  ['L', KeyboardKey.L],
  ['Z', KeyboardKey.Z],
  ['X', KeyboardKey.X],
  ['C', KeyboardKey.C],
  ['V', KeyboardKey.V],
  ['B', KeyboardKey.B],
  ['N', KeyboardKey.N],
  ['M', KeyboardKey.M],
  ['`', KeyboardKey.Backtick],
  ['~', KeyboardKey.Tilde],
  ['!', KeyboardKey.ExclamationPoint],
  ['@', KeyboardKey.AtSymbol],
  ['#', KeyboardKey.HashSign],
  ['$', KeyboardKey.DollarSign],
  ['%', KeyboardKey.Percent],
  ['^', KeyboardKey.Caret],
  ['&', KeyboardKey.Ampersand],
  ['*', KeyboardKey.Asterix],
  ['(', KeyboardKey.LeftParenthesis],
  [')', KeyboardKey.RightParenthesis],
  ['-', KeyboardKey.Dash],
  ['_', KeyboardKey.Underscore],
  ['=', KeyboardKey.Equals],
  ['+', KeyboardKey.Plus],
  ['[', KeyboardKey.LeftSquareBracket],
  [']', KeyboardKey.RightSquareBracket],
  ['{', KeyboardKey.LeftCurlyBrace],
  ['}', KeyboardKey.RightCurlyBrace],
  ['\\', KeyboardKey.BackSlash],
  ['|', KeyboardKey.PipeSymbol],
  [';', KeyboardKey.Semicolon],
  [':', KeyboardKey.Colon],
  ['\'', KeyboardKey.BackSlash],
  ['"', KeyboardKey.DoubleQuote],
  [',', KeyboardKey.Comma],
  ['.', KeyboardKey.Period],
  ['<', KeyboardKey.LessThan],
  ['>', KeyboardKey.GreaterThan],
  ['/', KeyboardKey.ForwardSlash],
  ['?', KeyboardKey.QuestionMark]
]);